### ISSUE TITLE
Geomesa-quickstart-accumulo tutorial error for creating schema

### ISSUE THREAD

**Issue by nik-ffm** [geomesa/geomesa-tutorials#1]
When the code hits the line: `dataStore.createSchema(simpleFeatureType);`  it gives:

```Creating feature-type (schema):  AccumuloQuickStart
Starting
State change: CONNECTED
Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: Invalid method name: 'beginTableOperation'
	at org.apache.accumulo.core.client.admin.TableOperationsImpl.doTableOperation(TableOperationsImpl.java:314)
	at org.apache.accumulo.core.client.admin.TableOperationsImpl.doTableOperation(TableOperationsImpl.java:282)
	at org.apache.accumulo.core.client.admin.TableOperationsImpl.create(TableOperationsImpl.java:210)
	at org.locationtech.geomesa.accumulo.AccumuloVersion$.ensureTableExists(AccumuloVersion.scala:74)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.ensureTableExists(GeoMesaMetadata.scala:67)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.writeMutations(GeoMesaMetadata.scala:105)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.insert(GeoMesaMetadata.scala:198)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.writeMetadata(AccumuloDataStore.scala:149)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:275)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:65)
	at com.example.geomesa.accumulo.AccumuloQuickStart.main(AccumuloQuickStart.java:322)
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'beginTableOperation'
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.apache.accumulo.core.master.thrift.MasterClientService$Client.recv_beginTableOperation(MasterClientService.java:467)
	at org.apache.accumulo.core.master.thrift.MasterClientService$Client.beginTableOperation(MasterClientService.java:453)
	at org.apache.accumulo.core.client.admin.TableOperationsImpl.beginTableOperation(TableOperationsImpl.java:222)
	at org.apache.accumulo.core.client.admin.TableOperationsImpl.doTableOperation(TableOperationsImpl.java:290)
	... 10 more```

Just followed the the tutorial, Accumulo: 1.6.4, Geomesa 1.5, Hadoop: 2.6, ZK: 3.4.6

**Comment by elahrvivaz** [comment]
That exception means your version of accumulo is mismatched - you'll have to change the pom in the quickstart to match your version (by default it uses 1.5):
https://github.com/geomesa/geomesa-tutorials/blob/master/pom.xml#L37
We should probably document the expected versions better.

**Comment by elahrvivaz** [comment]
@nik-ffm I've updated the documentation - I'm going to close this issue. Please let me know if you have any more problems.

**Comment by nik-ffm** [comment]
Well, almost. Would be great if you could also update the reference to the jar to `geomesa-gdelt-1.2.0-SNAPSHOT.jar` in the `GDELTIngest.java` file (lines 147 and 153). But then it seems to work for me :+1:

**Comment by elahrvivaz** [comment]
@nik-ffm thanks, we're working on updating the tutorials now, and will be sure to fix that.

**Comment by nik-ffm** [comment]
@elahrvivaz  I also have trouble following the spark tutorial. Where shall I note my problems? That tutorial isn't migrated to this repo yet. Shall I use the mailing list, create issues here (issues isn't available to me in the main repo) or use something totaly different?

**Comment by elahrvivaz** [comment]
@nik-ffm I would use the mailing list - we can create issues from that in the geomesa JIRA and track them there. In the meantime, there are some code snippets in the README that should be more up-to-date, and might get you started: https://github.com/locationtech/geomesa/tree/master/geomesa-compute
