### ISSUE TITLE
BoxesRuntime out of bound.

### ISSUE THREAD

**Issue by zhouhoo** [geomesa/geomesa-tutorials#34]
I  modifed geomesa-quickstart-hbase example to go further ,I changed simpleFeatureTpye  field Point:srid=4326 to LineStrig:4326,  which means I want to save a collection of  trace points.  

the code is here :

```
public static SimpleFeatureType createSimpleFeatureTypeEx(String simpleFeatureTypeName)
            throws SchemaException {
        List<String> attributes = Lists.newArrayList(

                "VID:String",

                "BoxNum:String",

                "TripID:String",

                "ST1:Date",

                "ST2:String",

                "ET1:Date",

                "ET2:String",

                "*Trace:LineString:srid=4326" // the "*" denotes the default geometry (used for indexing)

        );
```
I use the test tarces data of size 21335   for all x=116.37 ,y=45.2 .  
but I got error like this.

`Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Values out of bounds ([-180.0 180.0] [-90.0 90.0] [0.0 604800.0]): [116.37 116.37] [45.2 45.2] [-28800.0 -28800.0]
	at scala.Predef$.require(Predef.scala:219)
	at org.locationtech.geomesa.curve.XZ3SFC.org$locationtech$geomesa$curve$XZ3SFC$$normalize(XZ3SFC.scala:353)
	at org.locationtech.geomesa.curve.XZ3SFC.index(XZ3SFC.scala:63)
	at org.locationtech.geomesa.index.index.XZ3Index$class.org$locationtech$geomesa$index$index$XZ3Index$$getRowKey(XZ3Index.scala:73)
	at org.locationtech.geomesa.index.index.XZ3Index$$anonfun$writer$1.apply(XZ3Index.scala:44)
	at org.locationtech.geomesa.index.index.XZ3Index$$anonfun$writer$1.apply(XZ3Index.scala:44)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureWriter$$anonfun$writeFeature$1.apply(GeoMesaFeatureWriter.scala:134)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureWriter$$anonfun$writeFeature$1.apply(GeoMesaFeatureWriter.scala:134)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureWriter.writeFeature(GeoMesaFeatureWriter.scala:134)
	at org.locationtech.geomesa.index.geotools.GeoMesaAppendFeatureWriter$class.write(GeoMesaFeatureWriter.scala:194)
	at org.locationtech.geomesa.hbase.data.HBaseAppendFeatureWriter.write(HBaseFeatureWriter.scala:21)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureStore.addFeatures(GeoMesaFeatureStore.scala:44)
	at com.example.geomesa.hbase.SmartDriveLine.insertFeatures(SmartDriveLine.java:157)
	at com.example.geomesa.hbase.SmartDriveLine.main(SmartDriveLine.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

I did not set [-28800.0 -28800.0], how did this come out? 
What is more confusing is that  When I look data in Hbase, I insert about 17072 rows data!!!  which is not equal to 0 or 21355.

**Comment by elahrvivaz** [comment]
The 3rd number is the normalized time - I'm guessing that you are inserting dates before the java epoch (1970) - that is not currently supported.

**Comment by elahrvivaz** [comment]
@zhouhoo re-open if you have any further issues. Thanks,
