### ISSUE TITLE
Geomesa Spark tutorial: CountByDay

### ISSUE THREAD

**Issue by sandeep-iitr** [geomesa/geomesa-tutorials#45]
I am trying to use spark in Geomesa following the CountByDay tutorial. I have successfully ingested some GDELT data.
The problem I ran into is as below. Any help is appreciated:

```
Exception in thread "main" java.io.IOException: Schema 'gdelt' has not been initialized. Please call 'createSchema' first.
	at org.locationtech.geomesa.index.geotools.GeoMesaDataStore.getQueryPlan(GeoMesaDataStore.scala:462)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.getQueryPlan(AccumuloDataStore.scala:108)
	at org.locationtech.geomesa.jobs.accumulo.AccumuloJobUtils$.getMultipleQueryPlan(AccumuloJobUtils.scala:117)
	at org.locationtech.geomesa.spark.accumulo.AccumuloSpatialRDDProvider.rdd(AccumuloSpatialRDDProvider.scala:107)
	at com.example.geomesa.spark.CountByDay$.main(CountByDay.scala:59)
	at com.example.geomesa.spark.CountByDay.main(CountByDay.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/04/23 19:55:05 INFO SparkContext: Invoking stop() from shutdown hook
```

**Comment by elahrvivaz** [comment]
You are getting that exception because it can't find the schema. Usually that will occur if your connection parameters are not exactly the same. Can you double check that you have used the same table (including namespace) and feature name?

**Comment by sandeep-iitr** [comment]
Thanks for your reply, I will look into it.

**Comment by supamanda** [comment]
In our case, the feature name should have been "event" instead of "gdelt", because the config in the hadoop command of the ingest tutorial (http://www.geomesa.org/documentation/tutorials/geomesa-examples-gdelt.html) says: "-tableName gdelt -featureName event "
