### ISSUE TITLE
accumulo filter query erro， help！！！

### ISSUE THREAD

**Issue by Xebin** [geomesa/geomesa-tutorials#6]
first i have add geomesa-accumulo-distributed-runtime-1.2.2-SNAPSHOT.jar to accumulo lib. however when i run geomesa-quickstart-accumulo ，erros ：
  

 exception while doing multi-scan 
	java.lang.NoClassDefFoundError: Could not initialize class org.locationtech.geomesa.utils.geotools.package$
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$GeomAttributeSpec.addOptions(SimpleFeatureTypes.scala:395)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$AttributeSpec$class.toAttribute(SimpleFeatureTypes.scala:222)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$GeomAttributeSpec.toAttribute(SimpleFeatureTypes.scala:378)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$$anonfun$createType$1.apply(SimpleFeatureTypes.scala:129)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$$anonfun$createType$1.apply(SimpleFeatureTypes.scala:129)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.immutable.List.foreach(List.scala:381)
		at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
		at scala.collection.immutable.List.map(List.scala:285)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$.createType(SimpleFeatureTypes.scala:129)
		at org.locationtech.geomesa.utils.geotools.SimpleFeatureTypes$.createType(SimpleFeatureTypes.scala:93)
		at org.locationtech.geomesa.accumulo.iterators.KryoLazyFilterTransformIterator.init(KryoLazyFilterTransformIt

**Comment by Xebin** [comment]
it has confused me a day, thanks for replying....

**Comment by Xebin** [comment]
when change 		FeatureIterator featureItr = featureSource.getFeatures(query).features();     ==>  		FeatureIterator featureItr = featureSource.getFeatures(	).features();  ,  the  program runs well.

**Comment by elahrvivaz** [comment]
Likely the jars are not installed properly - when you do not apply any filters or transforms, then there are no accumulo server-side iterators that get applied, so therefore you are bypassing the classpath error. Do you have any other jars installed in accumulo that might be conflicting? Are you sure that the jar is installed on each of your tablet servers?

**Comment by Xebin** [comment]
thanks for your replying, i have fixed it.   when i changed hadoop-2-4.0 to hadoop-2-7.2,the peogram runed well

**Comment by elahrvivaz** [comment]
Sounds good, thanks.
