### ISSUE TITLE
Geomesa spark: no such method: sendBaseOneway

### ISSUE THREAD

**Issue by alicjusz23** [geomesa/geomesa-tutorials#63]
Hello,

I have encountered a problem while submitting spark job:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.sendBaseOneway(Ljava/lang/String;Lorg/apache/thrift/TBase;)V
    at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.send_closeScan(TabletClientService.java:303)
    at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.closeScan(TabletClientService.java:295)
    at org.apache.accumulo.core.client.impl.ThriftScanner.getBatchFromServer(ThriftScanner.java:117)
    at org.apache.accumulo.core.metadata.MetadataLocationObtainer.lookupTablet(MetadataLocationObtainer.java:101)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:483)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:654)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:640)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.locateTablet(TabletLocatorImpl.java:456)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocation(TabletLocatorImpl.java:480)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.lookupTabletLocationAndCheckLock(TabletLocatorImpl.java:654)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl._locateTablet(TabletLocatorImpl.java:640)
    at org.apache.accumulo.core.client.impl.TabletLocatorImpl.locateTablet(TabletLocatorImpl.java:456)
    at org.apache.accumulo.core.client.impl.ThriftScanner.scan(ThriftScanner.java:247)
    at org.apache.accumulo.core.client.impl.ScannerIterator$Reader.run(ScannerIterator.java:79)
    at org.apache.accumulo.core.client.impl.ScannerIterator.hasNext(ScannerIterator.java:150)
    at org.locationtech.geomesa.accumulo.data.AccumuloMetadataAdapter$class.scanValue(AccumuloBackedMetadata.scala:70)
    at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.scanValue(AccumuloBackedMetadata.scala:22)
    at org.locationtech.geomesa.index.metadata.CachedLazyMetadata$$anon$1.load(CachedLazyMetadata.scala:50)
    at org.locationtech.geomesa.index.metadata.CachedLazyMetadata$$anon$1.load(CachedLazyMetadata.scala:46)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3308)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2031)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2029)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2012)
    at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
    at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
    at org.locationtech.geomesa.index.metadata.CachedLazyMetadata$class.read(CachedLazyMetadata.scala:82)
    at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.read(AccumuloBackedMetadata.scala:22)
    at org.locationtech.geomesa.index.geotools.MetadataBackedDataStore.getSchema(MetadataBackedDataStore.scala:181)
    at org.locationtech.geomesa.index.geotools.GeoMesaDataStore.getSchema(GeoMesaDataStore.scala:189)
    at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.getSchema(AccumuloDataStore.scala:221)
    at org.locationtech.geomesa.spark.accumulo.AccumuloSpatialRDDProvider.rdd(AccumuloSpatialRDDProvider.scala:151)
    at com.example.geomesa.spark.CountByDay$.main(CountByDay.scala:59)
    at com.example.geomesa.spark.CountByDay.main(CountByDay.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I don't know how to resolve it.

**Comment by elahrvivaz** [comment]
likely the version of accumulo in your spark job does not match the version of accumulo you are querying. Did you update `accumulo.version` in the `pom.xml` before building?

**Comment by alicjusz23** [comment]
Yes, I have updated it in pom.xml . I am using accumulo 1.8.1 , hadoop 2.7.4 , zookeeper 3.4.10 and spark 2.0.0 .
I am submitting job with command:
/path/to/spark/bin/spark-submit --master yarn \
  --class com.example.geomesa.spark.CountByDay \
  /.../geomesa-tutorials/geomesa-examples-spark/target/geomesa-examples-spark-2.0.0-SNAPSHOT.jar

When I submit job locally (--master local), it works, but with yarn it shows such an error.

**Comment by elahrvivaz** [comment]
do you have any other accumulo jars in your spark classpath? Also, you may want to use spark 2.2.0, that is the version targeted by geomesa 2.0.x

**Comment by alicjusz23** [comment]
> do you have any other accumulo jars in your spark classpath?
I am not sure, how can I check it?

**Comment by elahrvivaz** [comment]
@alicjusz23 any more updates? I think that this is a configuration issue, more than a bug per-say. Is it ok to close the issue? If you need additional help, you can get more real-time responses in our gitter channel: https://gitter.im/locationtech/geomesa

**Comment by alicjusz23** [comment]
Thank you very much for help. Partially it run forward but still having some problems. Yes, we can close the issue and better I will write on gitter.

**Comment by jrs53** [comment]
Think this is thrift 0.9.3 Vs 0.9.1
