### ISSUE TITLE
Failed to create schema to hbase datastore with pseudo distribution mode

### ISSUE THREAD

**Issue by qub01** [geomesa/geomesa-tutorials#72]
Hi GeoMesa Devs,

I am encountering issue when trying to create schema by using geomesa-hbase. "geomesa-hbase create-schema" works fine when I am using hbase with standalone mode.  But it keeps reporting errors when I change hbase-site.xml configuration to make hbase using hdfs. 

hbase shell works fine, I can read and write data into hdfs via hbase shell. But geomesa-hbase reporting the following error . Could you help to tell me how to make it work? It seems to me that the tool could not connection to hbase, I tried to put the hbase-site.xml into geomesa-hbase-datastore JAR  under lib dir but still see the issue.

```
~/geomesa/geomesa-hbase_2.11-2.0.2/bin/geomesa-hbase create-schema -c elemeodps1 -s /home/qubin.qb/geomesa/geomesa-hbase_2.11-2.0.2/conf/sfts/elemeodps/reference.conf
Error while parsing JAI registry file "file:/home/qubin.qb/hbase-1.4.6/lib/geomesa-hbase-distributed-runtime_2.11-2.0.2.jar!/META-INF/registryFile.jai" :
Error in registry file at line number #31
A descriptor is already registered against the name "org.geotools.ColorReduction" under registry mode "rendered"
Error in registry file at line number #32
A descriptor is already registered against the name "org.geotools.ColorInversion" under registry mode "rendered"
ERROR java.io.IOException: java.lang.reflect.InvocationTargetException
java.util.concurrent.CompletionException: java.io.IOException: java.lang.reflect.InvocationTargetException
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:929)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$.getConnection(HBaseConnectionPool.scala:86)
        at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:44)
        at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:34)
        at org.geotools.data.DataAccessFinder.getDataStore(DataAccessFinder.java:130)
        at org.geotools.data.DataStoreFinder.getDataStore(DataStoreFinder.java:89)
        at org.locationtech.geomesa.tools.DataStoreCommand$class.withDataStore(Command.scala:57)
        at org.locationtech.geomesa.hbase.tools.data.HBaseCreateSchemaCommand.withDataStore(HBaseCreateSchemaCommand.scala:19)
        at org.locationtech.geomesa.tools.data.CreateSchemaCommand$class.execute(CreateSchemaCommand.scala:30)
        at org.locationtech.geomesa.hbase.tools.data.HBaseCreateSchemaCommand.execute(HBaseCreateSchemaCommand.scala:19)
        at org.locationtech.geomesa.tools.Runner$class.main(Runner.scala:28)
        at org.locationtech.geomesa.hbase.tools.HBaseRunner$.main(HBaseRunner.scala:21)
        at org.locationtech.geomesa.hbase.tools.HBaseRunner.main(HBaseRunner.scala)
Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:3207)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2$$anon$4.run(HBaseConnectionPool.scala:57)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2$$anon$4.run(HBaseConnectionPool.scala:53)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2.load(HBaseConnectionPool.scala:64)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2.load(HBaseConnectionPool.scala:50)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922)
        ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        ... 25 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.tracing.TraceUtils.wrapHadoopConf(Ljava/lang/String;Lorg/apache/hadoop/conf/Configuration;)Lorg/apache/htrace/HTraceConfiguration;
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:636)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2812)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2849)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2831)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.initTempDir(DynamicClassLoader.java:120)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:98)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:252)
        at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:945)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:721)
        ... 30 more
```
And here is the hbase-site.xml I use

- hbase-site.xml for standalone mode which works fine for me. geomesa_hbase tool can read/write data even without put hbase-site.xml into geomesa-hbase-datastore JAR :
```
    <property>
        <name>hbase.rootdir</name>
        <value>file:///home/qubin.qb/hbase-1.4.6/HBASE/hbase</value>
    </property>

    <property>
        <name>hbase.zookeeper.property.dataDir</name>
        <value>/home/qubin.qb/hbase-1.4.6/HBASE/zookeeper</value>
    </property>
    <property>
        <name>hbase.zookeeper.property.clientPort</name>
        <value>2181</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>x.x.x.x</value>
    </property>
    -->
```
- hbase-site.xml for  pseudo distributed mode: this time there is no luck, always see above exception when create schema
```
    <property>
        <name>hbase.rootdir</name>
        <value>hdfs://x.x.x.x:9000/hbase</value>
    </property>
    <property>
        <name>hbase.cluster.distributed</name>
        <value>true</value>
    </property>
    <property>
        <name>hbase.zookeeper.property.clientPort</name>
        <value>2181</value>
    </property>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>x.x.x.x</value>
    </property>
```

Thanks a lot, a lot!

**Comment by elahrvivaz** [comment]
This seems to be an issue with the classpath. You can use `./geomesa-hbase classpath` to see what jars are being loaded. By default, the script will try to load things from various environment variables, e.g. `HBASE_HOME` and `HADOOP_HOME`. What version of hbase and hadoop are you using?

Generally, it may work if you use the included `bin/install-hadoop.sh` and `bin/install-hbase.sh` scripts to download hadoop 2.8.4 and hbase 1.3.1 jars, and exclude `HBASE_HOME` and `HADOOP_HOME` from your classpath (the easiest way is to `unset` them in your bash shell). The 2.8.4/1.3.1 jars tend to work with whatever version of hbase and hadoop you are actually using.

**Comment by qub01** [comment]
hadoop version is 2.8.4
HBase version is 1.4.6

I will exclude the class path and retest the case.

Thanks!

**Comment by elahrvivaz** [comment]
@santhoshgitdevops did you follow my suggestion to unset `HBASE_HOME`, etc?

**Comment by dongwei0227** [comment]
@santhoshgitdevops,I have same prombles,did you resolve it?

**Comment by dongwei0227** [comment]
@qub01,@santhoshgitdevops,I have same problem,did you resolve it?

**Comment by santhoshgitdevops** [comment]
Hi, yes i am able to create schema but we had issue with kerberos while
ingesting data into it.

**Comment by elahrvivaz** [comment]
kerberos should work for local ingest but no one has worked through how to do a distributed ingest yet: https://geomesa.atlassian.net/browse/GEOMESA-2604

**Comment by dongwei0227** [comment]
@santhoshgitdevops ,Can you tell me how to do with this problem?Thanks!

**Comment by dongwei0227** [comment]
@santhoshgitdevops ,can you tell me how to do with this problem?Thanks!
I use :
hadoop version is 2.7.6
HBase version is 1.4.4
geomesa 2.3.0
zookeeper 3.4.13

**Comment by elahrvivaz** [comment]
@dongwei0227 did you try my original suggestion, [above](https://github.com/geomesa/geomesa-tutorials/issues/72#issuecomment-441639817)?

**Comment by santhoshgitdevops** [comment]
Hi, what exactly are you trying to do ? What error you got ?

**Comment by dongwei0227** [comment]
@elahrvivaz,@santhoshgitdevops ,thanks!
I have unset hadoop_home and hbase_home。
step1:    
[root@master ~]# unset HADOOP_HOME
[root@master ~]# unset HBASE_HOME
[root@master ~]# echo $HADOOP_HOME

[root@master ~]# echo $HBASE_HOME

[root@master ~]# geomesa-hbase classpath
step2:
[root@master ~]# geomesa-hbase classpath
/home/geomesa-hbase_2.11-2.3.0/conf
/home/geomesa-hbase_2.11-2.3.0/lib/accessors-smart-1.1.jar
/home/geomesa-hbase_2.11-2.3.0/lib/aircompressor-0.10.jar
/home/geomesa-hbase_2.11-2.3.0/lib/arrow-format-0.10.0.jar
......
/home/hbase-1.4.4
/home/hadoop-2.7.6
step3:
[root@master ~]# geomesa-hbase ingest --catalog laneline_shape_test --feature-name laneline_shape_test --input-format shp  "/mnt/shape/HA_LaneLine.shp"
step4:
INFO  No converter defined - will attempt to detect schema from input files
INFO  Inferred schema: laneline_shape_test identified *the_geom:MultiLineString
INFO  Inferred converter:
{
    "fields" : [
        {
            "name" : "the_geom",
            "transform" : "$1"
        }
    ],
    "id-field" : "$0",
    "options" : {
        "encoding" : "UTF-8",
        "error-mode" : "skip-bad-records",
        "parse-mode" : "incremental",
        "validators" : [
            "index"
        ]
    },
    "type" : "shp"
}

Use inferred converter (y/n)? y
Persist this converter for future use (y/n)? y
step5:
INFO  Added import in reference.conf and saved inferred schema and converter to /home/geomesa-hbase_2.11-2.3.0/conf/laneline_shape_test_14.conf
INFO  In future commands, the schema and converter may be invoked with '--spec laneline_shape_test' and '--converter laneline_shape_test'
ERROR java.io.IOException: java.lang.reflect.InvocationTargetException
java.util.concurrent.CompletionException: java.io.IOException: java.lang.reflect.InvocationTargetException
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:929)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$.getConnection(HBaseConnectionPool.scala:86)
        at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:45)
        at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:35)
        at org.geotools.data.DataAccessFinder.getDataStore(DataAccessFinder.java:121)
        at org.geotools.data.DataStoreFinder.getDataStore(DataStoreFinder.java:71)
        at org.locationtech.geomesa.tools.ingest.AbstractConverterIngest.run(AbstractConverterIngest.scala:29)
        at org.locationtech.geomesa.tools.ingest.IngestCommand$$anonfun$execute$3.apply(IngestCommand.scala:107)
        at org.locationtech.geomesa.tools.ingest.IngestCommand$$anonfun$execute$3.apply(IngestCommand.scala:106)
        at scala.Option.foreach(Option.scala:257)
        at org.locationtech.geomesa.tools.ingest.IngestCommand$class.execute(IngestCommand.scala:106)
        at org.locationtech.geomesa.hbase.tools.ingest.HBaseIngestCommand.execute(HBaseIngestCommand.scala:23)
        at org.locationtech.geomesa.tools.Runner$class.main(Runner.scala:28)
        at org.locationtech.geomesa.hbase.tools.HBaseRunner$.main(HBaseRunner.scala:21)
        at org.locationtech.geomesa.hbase.tools.HBaseRunner.main(HBaseRunner.scala)
Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:3207)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2$$anon$4.run(HBaseConnectionPool.scala:57)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2$$anon$4.run(HBaseConnectionPool.scala:53)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2.load(HBaseConnectionPool.scala:64)
        at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$2.load(HBaseConnectionPool.scala:50)
        at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922)
        ... 19 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        ... 27 more
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2204)
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2169)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2265)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2291)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:714)
        ... 32 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.EventLoopGroup
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by dongwei0227** [comment]
@elahrvivaz,@santhoshgitdevops ,I have resolve it.Thank you very much!
I copy these jar from hadoop to geomesa/lib,then it's ok!
commons-cli-1.2.jar
commons-io-2.4.jar
hadoop-common-2.7.6.jar
hadoop-hdfs-2.7.6.jar
hadoop-mapreduce-client-app-2.7.6.jar
hadoop-mapreduce-client-common-2.7.6.jar
hadoop-mapreduce-client-core-2.7.6.jar
hadoop-yarn-api-2.7.6-sources.jar
hadoop-yarn-api-2.7.6.jar
hadoop-yarn-applications-distributedshell-2.7.6.jar
hadoop-yarn-client-2.7.6.jar
hadoop-yarn-common-2.7.6.jar
hadoop-yarn-registry-2.7.6.jar
hadoop-yarn-server-common-2.7.6.jar
hamcrest-core-1.3.jar
htrace-core-3.1.0-incubating.jar
metrics-core-2.2.0.jar
netty-all-4.1.8.Final.jar
protobuf-java-2.5.0.jar

**Comment by santhoshgitdevops** [comment]
That's great. I was busy so late reply.

**Comment by santhoshgitdevops** [comment]
@ dongwei0227
Are you using kerberos ?
