### ISSUE TITLE
Problems with geomesa-quickstart-accumulo

### ISSUE THREAD

**Issue by PietroProraso** [geomesa/geomesa-tutorials#8]
Hello,

From CDH 5 I installed
zookepper 3.4.5
hadoop 2.6.0
and I installed accumulo 1.6.0 manually

I updated the pom.xml with the above and use 
```
 <source>1.7</source>
<target>1.7</target>
```
because I use java-7-openjdk

When I want to start the tutorial, I get the following error:
```
$ java -cp geomesa-quickstart-accumulo/target/geomesa-quickstart-accumulo-1.2.2.jar com.example.geomesa.accumulo.AccumuloQuickStart -instanceId GIS -zookeepers localhost:2181 -user root -password *** -tableName tab1
Creating feature-type (schema):  AccumuloQuickStart
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.curator.utils.PathUtils.validatePath(Ljava/lang/String;)Ljava/lang/String;
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.<init>(InterProcessSemaphoreV2.java:119)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.<init>(InterProcessSemaphoreV2.java:103)
	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreMutex.<init>(InterProcessSemaphoreMutex.java:40)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.acquireDistributedLock(AccumuloDataStore.scala:658)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:109)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:62)
	at com.example.geomesa.accumulo.AccumuloQuickStart.main(AccumuloQuickStart.java:324)
```

I would be very happy if I can get this to run!

**Comment by elahrvivaz** [comment]
Could you check your maven dependency tree and ensure that curator-client, curator-framework and curator-recipes are all version 2.7.1?

**Comment by PietroProraso** [comment]
I ran
`$ mvn dependency:tree `
in the tutorials folder

and the log shows
```
[INFO] |  +- org.apache.curator:curator-client:jar:2.6.0:compile
[...]
[INFO] |  +- org.apache.curator:curator-recipes:jar:2.7.1:compile
[INFO] |  |  \- org.apache.curator:curator-framework:jar:2.7.1:compile
```

**Comment by elahrvivaz** [comment]
I believe that some change you have made to the pom has changed the curator client version. Try adding a dependencyManagement section to set the version explicitly to 2.7.1.

**Comment by PietroProraso** [comment]
I added
```
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-client</artifactId>
                <version>2.7.1</version>
            </dependency>
```
to the dependencyManagement in pom.xml.
Now I get:

```
Creating feature-type (schema):  AccumuloQuickStart
Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: Internal error processing waitForFateOperation
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:336)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:293)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doTableFateOperation(TableOperationsImpl.java:1570)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.create(TableOperationsImpl.java:220)
	at org.locationtech.geomesa.accumulo.AccumuloVersion$.ensureTableExists(AccumuloVersion.scala:74)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.ensureTableExists(GeoMesaMetadata.scala:70)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.writeMutations(GeoMesaMetadata.scala:108)
	at org.locationtech.geomesa.accumulo.data.AccumuloBackedMetadata.insert(GeoMesaMetadata.scala:201)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.writeMetadata(AccumuloDataStore.scala:617)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:118)
	at org.locationtech.geomesa.accumulo.data.AccumuloDataStore.createSchema(AccumuloDataStore.scala:62)
	at com.example.geomesa.accumulo.AccumuloQuickStart.main(AccumuloQuickStart.java:324)
Caused by: org.apache.thrift.TApplicationException: Internal error processing waitForFateOperation
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.apache.accumulo.core.master.thrift.FateService$Client.recv_waitForFateOperation(FateService.java:172)
	at org.apache.accumulo.core.master.thrift.FateService$Client.waitForFateOperation(FateService.java:157)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.waitForFateOperation(TableOperationsImpl.java:265)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:307)
	... 11 more

```

The changes I made from the distributed pom.xml are:
```
[...]
        <!-- environment specific variables-->
        **<accumulo.version>1.6.0</accumulo.version>
        <zookeeper.version>3.4.5</zookeeper.version>
        <hadoop.version>2.6.0</hadoop.version>
        <kafka.version>0.8.2.2</kafka.version>
        <storm.version>0.9.3</storm.version>**
    </properties>

[...]

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    **<source>1.7</source>**
                    **<target>1.7</target>**
                </configuration>
            </plugin>

```

**Comment by elahrvivaz** [comment]
I would try reverting the hadoop version back to the original value (2.2.0). Hadoop is generally compatible across versions, but it can mess up your dependency tree.

**Comment by PietroProraso** [comment]
I tried setting
`<hadoop.version>2.2.0</hadoop.version>`
in pom.xml (keeping the hadoop 2.6.0 installation).

Same error as before:
`Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: Internal error processing waitForFateOperation
[...]
`

**Comment by elahrvivaz** [comment]
do you see anything in your accumulo logs?

**Comment by PietroProraso** [comment]
oh my gosh.

I forgot to check if passwordless ssh was really working for the accumulo user - which was not the case.
It seems to work now.

many thanks to you, elahrvivaz, nevertheless for your help

**Comment by elahrvivaz** [comment]
good to hear, thanks.
